### ISSUE TITLE
LFU: Allow setting the frequency and update the heap

### ISSUE THREAD

**Issue by ilius** [Code-Hex/go-generics-cache#34]
I have a dictionary in which I want to keep the 20 most frequent words / queries for example. So I make a LFU cache:
```go
frequency = lfu.NewCache[string, int](lfu.WithCapacity(20))
```

and then
```go
count, _ := frequency.Get(query)
frequency.Set(query, count+1)
```

on every query.
So when it exceeds 20, the least frequent query is deleted.
And I can save this to a JSON file as well.
So far so good.

But when I run the program next time and load this JSON file, and set the values, the internal frequency (heap order) is not updated (they are all one) unless I run `Get()` or `Set()` the same number of times (or at least `N` times for the top item, if we have `N` items), which is very slow.

So if I could run `frequency.SetWithCount(key, value, count)` for example, that is just like
```go
for i:=0; i<count; i++ {
    frequency.Set(key, value)
}
```
But much faster.
That would solve the problem.

**Comment by Code-Hex** [comment]
@ilius I just released the latest version for this
https://github.com/Code-Hex/go-generics-cache/releases/tag/v1.3.0

**Comment by ilius** [comment]
Thanks.
