### ISSUE TITLE
Slow expiration key clearing

### ISSUE THREAD

**Issue by RelicOfTesla** [Code-Hex/go-generics-cache#47]
Don't use full keys scan........

**Comment by Code-Hex** [comment]
@RelicOfTesla Do you have any plans?

**Comment by Code-Hex** [comment]
@RelicOfTesla I have released v1.4.0.

**Comment by RelicOfTesla** [comment]
Still scanning with full key??? You only need to check if the top items in the priority queue have expired.

**Comment by RelicOfTesla** [comment]
```go
func (c *Cache[K, V]) DeleteExpired() {
	now := time.Now()
	c.mu.Lock()
	defer c.mu.Unlock()
	for {
		t := c.expManager.top()
		if t != nil && now.After(t.expiration) {
			c.expManager.remove(t.key)
		} else {
			break
		}
	}
	return
}

func (m *expirationManager[K]) top() *expirationKey[K] {
	if m.len() == 0 {
		return nil
	}
	return m.queue[0]
}
```

**Comment by Code-Hex** [comment]
@RelicOfTesla not all scaning

https://github.com/Code-Hex/go-generics-cache/blob/5303a9aedb071542e9ec81b32c31704e0b9cabcc/cache.go#L231-L251

**Comment by RelicOfTesla** [comment]
Well, I read it wrong, but you only deleted one element from this one??

**Comment by Code-Hex** [comment]
@RelicOfTesla No, Please read my test cases. I tested them

https://github.com/Code-Hex/go-generics-cache/pull/48
