### ISSUE TITLE
LFU Delete/pop key take a long time

### ISSUE THREAD

**Issue by RelicOfTesla** [Code-Hex/go-generics-cache#55]
```go

func TestLFUPop(t *testing.T) {
	const maxKeySize = 10000000
	c := New[int, int](AsLFU[int, int](lfu.WithCapacity(maxKeySize)))
	take := time.Now()
	for i := 0; i < maxKeySize; i++ {
		c.Set(i, i)
	}
	t.Log(time.Since(take))

	take = time.Now()
	for i := 0; i < 300; i++ {
		c.Delete(i * 2)
	}
	t.Log(time.Since(take))
}

```
```
=== RUN   TestLFUPop
    cache_internal_test.go:366: 7.5215588s
    cache_internal_test.go:372: 11.4654817s   // delete 300 count key...used 11sec
```

**Comment by Code-Hex** [comment]
@RelicOfTesla Thanks for your creating issue!

Please write descriptions what do you think problem? What do you have expectation? What can I do for that?

If you have additional context, please write more describe. Thanks!

**Comment by Code-Hex** [comment]
profile
[profile.pb.gz](https://github.com/Code-Hex/go-generics-cache/files/14977359/profile.pb.gz)

**Comment by RelicOfTesla** [comment]
Do you think deleting 300 keys takes more than 10+ seconds is a normal result? 

Time-consuming code:
https://github.com/Code-Hex/go-generics-cache/blob/aac4f4743b3dcaff4b700f528d8d035b8986b1df/policy/lfu/priority_queue.go#L70-L74

**Comment by Code-Hex** [comment]
@RelicOfTesla I would appreciate it if you could be a little more polite in your issue. i.e. add profile

**Comment by RelicOfTesla** [comment]
Sorry, my English is not very good. I may have used inappropriate words semantically, which makes you feel uncomfortable.
