### ISSUE TITLE
Is this cache thread safe or not?

### ISSUE THREAD

**Issue by zhongdai** [Code-Hex/go-generics-cache#58]
I am a bit confused, in the README, it says it is thread safe, but I check the `NewCache()` methods, it says `non-thread safe`.

<img width="637" alt="image" src="https://github.com/Code-Hex/go-generics-cache/assets/4401438/f6dfa30c-472c-4e4a-a809-b1f49c15c625">

https://github.com/search?q=repo%3ACode-Hex%2Fgo-generics-cache%20NewCache&type=code
<img width="827" alt="image" src="https://github.com/Code-Hex/go-generics-cache/assets/4401438/54ee775c-2c29-4f57-b74b-35df11f09c1d">

**Comment by Code-Hex** [comment]
@zhongdai When using each policy via the cache package, it is thread-safe.

However, as the comment says, when using a policy alone, it is not thread-safe.
